#!/usr/bin/env bash

YEAR=2024
INTERACTIVE=false
SRC_DIR="src/Y${YEAR}"
DATA_DIR="data/Y${YEAR}"

start_ghci() {
    ghci ${SRC_DIR}/Day${1}
    exit 0
}

run_main() {
    runhaskell ${SRC_DIR}/Day${1}
    exit 0
}

create_files() {

    local data_path="${DATA_DIR}/Day${1}"
    local src_path="${SRC_DIR}/Day{1}.hs"

    # create input files
    mkdir -p $data_path
    if [ ! -f ${data_path}/sample.txt ] && [ ! -f ${data_path}/input.txt ]; then
        touch ${data_path}/sample.txt
        touch ${data_path}/input.txt
    fi
}

while getopts "r:i:c:" flag; do
    case $flag in
    r)
        echo "Running Day{OPTARG}.hs main function non-interactively"
        run_main ${OPTARG}
        ;;
    i)
        echo "Running Day{OPTARG}.hs interactively"
        start_ghci ${OPTARG}
        ;;
    c)
        echo "Creating Day${OPTARG}.hs From Template"
        create_files ${OPTARG}
        ;;
    \?)
        echo "Invalid option: -$OPTARG" >&2
        start_ghci $1
        exit 1
        ;;
    esac
    exit 0
done

# default with no flags
start_ghci $1
